insert into public.teams (espn_team_id, abbreviation, location, name, display_name) values
('22', 'ARI', 'Arizona', 'Cardinals', 'Arizona Cardinals'),
('1', 'ATL', 'Atlanta', 'Falcons', 'Atlanta Falcons'),
('33', 'BAL', 'Baltimore', 'Ravens', 'Baltimore Ravens'),
('2', 'BUF', 'Buffalo', 'Bills', 'Buffalo Bills'),
('29', 'CAR', 'Carolina', 'Panthers', 'Carolina Panthers'),
('3', 'CHI', 'Chicago', 'Bears', 'Chicago Bears'),
('4', 'CIN', 'Cincinnati', 'Bengals', 'Cincinnati Bengals'),
('5', 'CLE', 'Cleveland', 'Browns', 'Cleveland Browns'),
('6', 'DAL', 'Dallas', 'Cowboys', 'Dallas Cowboys'),
('7', 'DEN', 'Denver', 'Broncos', 'Denver Broncos'),
('8', 'DET', 'Detroit', 'Lions', 'Detroit Lions'),
('9', 'GB', 'Green Bay', 'Packers', 'Green Bay Packers'),
('34', 'HOU', 'Houston', 'Texans', 'Houston Texans'),
('11', 'IND', 'Indianapolis', 'Colts', 'Indianapolis Colts'),
('30', 'JAX', 'Jacksonville', 'Jaguars', 'Jacksonville Jaguars'),
('12', 'KC', 'Kansas City', 'Chiefs', 'Kansas City Chiefs'),
('13', 'LV', 'Las Vegas', 'Raiders', 'Las Vegas Raiders'),
('24', 'LAC', 'Los Angeles', 'Chargers', 'Los Angeles Chargers'),
('14', 'LAR', 'Los Angeles', 'Rams', 'Los Angeles Rams'),
('15', 'MIA', 'Miami', 'Dolphins', 'Miami Dolphins'),
('16', 'MIN', 'Minnesota', 'Vikings', 'Minnesota Vikings'),
('17', 'NE', 'New England', 'Patriots', 'New England Patriots'),
('18', 'NO', 'New Orleans', 'Saints', 'New Orleans Saints'),
('19', 'NYG', 'New York', 'Giants', 'New York Giants'),
('20', 'NYJ', 'New York', 'Jets', 'New York Jets'),
('21', 'PHI', 'Philadelphia', 'Eagles', 'Philadelphia Eagles'),
('23', 'PIT', 'Pittsburgh', 'Steelers', 'Pittsburgh Steelers'),
('26', 'SEA', 'Seattle', 'Seahawks', 'Seattle Seahawks'),
('25', 'SF', 'San Francisco', '49ers', 'San Francisco 49ers'),
('27', 'TB', 'Tampa Bay', 'Buccaneers', 'Tampa Bay Buccaneers'),
('10', 'TEN', 'Tennessee', 'Titans', 'Tennessee Titans'),
('28', 'WAS', 'Washington', 'Commanders', 'Washington Commanders')
on conflict (abbreviation) do update set
  espn_team_id = excluded.espn_team_id,
  location = excluded.location,
  name = excluded.name,
  display_name = excluded.display_name,
  active = true;
