import Link from "next/link";
import { notFound } from "next/navigation";
import { requireLeagueContext } from "@/lib/auth/context";
import { createUserClient } from "@/lib/supabase/server";
import { isEffectivelyLocked } from "@/lib/domain/deadline";

type Pick={result:string;selected_side:string;selected_team:{abbreviation:string}|null;game:{id:string;official_lines:Array<{home_spread:number;is_current:boolean}>}|null};
type Entry={id:string;tiebreaker_points:number;league_member:{display_name:string}|null;picks:Pick[]};
export default async function LivePage({params}:{params:Promise<{weekId:string}>}){const{weekId}=await params;await requireLeagueContext();const supabase=await createUserClient();const{data:week}=await supabase.from("weeks").select("id,nfl_week,status,lock_at").eq("id",weekId).maybeSingle();if(!week||!week.lock_at)notFound();const locked=isEffectivelyLocked(week.status,new Date(week.lock_at));if(!locked)return <main className="standalone-page"><Link href="/dashboard" className="back-link">← This week</Link><p className="eyebrow">POOL BOARD</p><h1>Picks stay private until lock.</h1><p className="page-lede">Come back after {formatDate(week.lock_at)} to see every submitted entry.</p></main>;
const{data:raw}=await supabase.from("entries").select("id,tiebreaker_points,league_member:league_members(display_name),picks(result,selected_side,selected_team:teams!picks_selected_team_id_fkey(abbreviation),game:games(id,official_lines(home_spread,is_current)))").eq("week_id",weekId).in("status",["SUBMITTED","LOCKED"]);const entries=(raw??[])as unknown as Entry[];return <main className="standalone-page"><Link href="/dashboard" className="back-link">← This week</Link><p className="eyebrow">LIVE POOL · WEEK {week.nfl_week}</p><h1>Everyone’s five.</h1><div className="pool-grid">{entries.map(entry=>{const correct=entry.picks.filter(pick=>pick.result==="CORRECT").length;const pending=entry.picks.filter(pick=>pick.result==="PENDING").length;const alive=entry.picks.every(pick=>pick.result==="CORRECT"||pick.result==="PENDING");return <article className="player-card" key={entry.id}><div className="player-card-head"><div><h2>{entry.league_member?.display_name}</h2><span>{correct} correct · {pending} pending</span></div><span className={alive?"alive":"eliminated"}>{alive?"Still alive":"Eliminated"}</span></div><ul>{entry.picks.map((pick,index)=>{const line=pick.game?.official_lines.find(candidate=>candidate.is_current);const spread=pick.selected_side==="HOME"?Number(line?.home_spread??0):-Number(line?.home_spread??0);return <li key={index}><strong>{pick.selected_team?.abbreviation} {formatSpread(spread)}</strong><span>{symbol(pick.result)}</span></li>})}</ul><footer>MNF prediction <strong>{entry.tiebreaker_points}</strong></footer></article>})}</div></main>}
function symbol(result:string){return result==="CORRECT"?"✓":result==="INCORRECT"?"✕":result==="PUSH"?"—":result==="VOID"?"VOID":"…"}
function formatSpread(value:number){return value===0?"PK":`${value>0?"+":""}${value}`}
function formatDate(value:string){return new Intl.DateTimeFormat("en-US",{weekday:"long",hour:"numeric",minute:"2-digit",timeZone:"America/New_York",timeZoneName:"short"}).format(new Date(value))}
