import Link from "next/link";
import { notFound,redirect } from "next/navigation";
import { PickForm,type PickGame } from "@/components/pick-form";
import { requireAdminContext } from "@/lib/auth/context";
import { createAdminClient } from "@/lib/supabase/admin";

type GameRow={id:string;kickoff_at:string;home_team:{abbreviation:string;display_name:string}|null;away_team:{abbreviation:string;display_name:string}|null;official_lines:Array<{home_spread:number;is_current:boolean}>};
export default async function CommissionerEntryPage({params,searchParams}:PageProps<"/admin/entries/[memberId]">){const{memberId}=await params;const query=await searchParams;const weekId=typeof query.weekId==="string"?query.weekId:null;if(!weekId)redirect("/admin/submissions");const context=await requireAdminContext();const admin=createAdminClient();const{data:member}=await admin.from("league_members").select("id,display_name,league_id").eq("id",memberId).eq("league_id",context.leagueId).maybeSingle();const{data:week}=await admin.from("weeks").select("id,nfl_week,status,lock_at,tiebreaker_game_id").eq("id",weekId).maybeSingle();if(!member||!week||!week.lock_at||week.status==="DRAFT"||week.status==="FINAL")notFound();await admin.from("audit_events").insert({league_id:context.leagueId,actor_user_id:context.userId,entity_type:"entry",entity_id:null,event_type:"PLAYER_ENTRY_OPENED_BY_COMMISSIONER",after_json:{week_id:weekId,member_id:memberId},reason:"Explicit View/Edit Entry action"});
const{data:rawGames}=await admin.from("games").select("id,kickoff_at,home_team:teams!games_home_team_id_fkey(abbreviation,display_name),away_team:teams!games_away_team_id_fkey(abbreviation,display_name),official_lines(home_spread,is_current)").eq("week_id",weekId).eq("is_selectable",true).order("kickoff_at");const rows=(rawGames??[])as unknown as GameRow[];const games:PickGame[]=rows.flatMap(row=>{const line=row.official_lines.find(candidate=>candidate.is_current);if(!row.home_team||!row.away_team||!line)return[];return[{id:row.id,kickoffAt:row.kickoff_at,home:{abbreviation:row.home_team.abbreviation,displayName:row.home_team.display_name},away:{abbreviation:row.away_team.abbreviation,displayName:row.away_team.display_name},homeSpread:Number(line.home_spread)}]});const{data:entry}=await admin.from("entries").select("id,tiebreaker_points").eq("week_id",weekId).eq("league_member_id",memberId).maybeSingle();const{data:existing}=entry?await admin.from("picks").select("game_id,selected_side").eq("entry_id",entry.id):{data:null};const initialPicks=Object.fromEntries((existing??[]).map(pick=>[pick.game_id,pick.selected_side]))as Record<string,"HOME"|"AWAY">;const tiebreaker=games.find(game=>game.id===week.tiebreaker_game_id);
return <main className="standalone-page pick-page"><Link href="/admin/submissions" className="back-link">← Submission status</Link><p className="eyebrow">EXPLICIT COMMISSIONER ACCESS</p><h1>{member.display_name}’s entry.</h1><p className="page-lede">Opening this page has been recorded. Saving requires a reason and creates a before/after audit event.</p><PickForm weekId={week.id} weekNumber={week.nfl_week} games={games} initialPicks={initialPicks} initialTiebreaker={entry?.tiebreaker_points??null} tiebreakerLabel={tiebreaker?`${tiebreaker.away.abbreviation} at ${tiebreaker.home.abbreviation}`:"Designated game"} lockAt={week.lock_at} locked={true} commissionerEdit={{memberId}}/></main>}
